# **Shortest Path Problem**

In [2]:
import numpy as np

In [3]:
V = range( 1, 7 )
E = [(1,2), (1,3), (2,3), (2,4), (3,5), (2, 5), (3,4), (5,4), (4,6), (5, 6)]
c = [ 4, 5, 3, 2, 3, 2, 2, 4, 5, 5 ]

In [4]:
oued = {i : [(k,j) for (k,j) in E if k == i ] for i in V}
ined = {i : [(k,j) for (k,j) in E if j == i ] for i in V}
cost = {E[i] : c[i] for i in range( len( E ) ) }

print( oued )
print( ined )
print( cost )

{1: [(1, 2), (1, 3)], 2: [(2, 3), (2, 4), (2, 5)], 3: [(3, 5), (3, 4)], 4: [(4, 6)], 5: [(5, 4), (5, 6)], 6: []}
{1: [], 2: [(1, 2)], 3: [(1, 3), (2, 3)], 4: [(2, 4), (3, 4), (5, 4)], 5: [(3, 5), (2, 5)], 6: [(4, 6), (5, 6)]}
{(1, 2): 4, (1, 3): 5, (2, 3): 3, (2, 4): 2, (3, 5): 3, (2, 5): 2, (3, 4): 2, (5, 4): 4, (4, 6): 5, (5, 6): 5}


In [5]:
def flux( i, ined, oued, x ) :
  f = 0
  for e in ined[i] :
    f = f + x[ e ]

  for e in oued[i] :
    f = f - x[ e ]

  return f

f = flux( 1, ined, oued, cost )
print( f )

-9


---
## **Dijkstra's Algorithm**

In [5]:
n = len( V )
print( n )

# 4 vertex
s = 1
l = {i : np.inf for i in V }
l[ s ] = 0
print( l )

p = { s: 0 }
print( p )

6
{1: 0, 2: inf, 3: inf, 4: inf, 5: inf, 6: inf}
{1: 0}


---
## **Moore-Bellman-Ford Algorithm**

In [6]:
def mbf_short_path( s, V, cost, oued ) :
  n = len( V )
  l = {i : np.inf for i in V }
  l[ s ] = 0
  p = { s: 0 }
  
  for i in range( 1, n ) :
    for ( i, j ) in oued[i] :
      cst = l[ i ] + cost[ ( i, j ) ]
      if l[ j ] > cst :
        l[ j ] = cst
        p[ j ] = i

  return [ l, p ]

def get_path( j, l, p ) : 
  k = j
  P = [j]
  while k != 0 :
    if p[k] != 0 :
      P.insert( 0, p[k] )
    k = p[k]

  return [ P, l ]

In [7]:
l, p = mbf_short_path( 1, V, cost, oued )

print( l )
print( p )

j = 6
P, PC = get_path( j, l, p )
print( P )
print( l[j] )

{1: 0, 2: 4, 3: 5, 4: 6, 5: 6, 6: 11}
{1: 0, 2: 1, 3: 1, 4: 2, 5: 2, 6: 4}
[1, 2, 4, 6]
11


---
# **Floyd-Warshall Algorithm**

In [8]:
def fw_short_path( V, E, cost ) :
  n = len( V )
  l = np.full( ( n, n ), np.inf )
  p = np.zeros( ( n, n ) )

  for ( i, j ) in E :
    l[ i-1, j-1 ] = cost[ ( i, j ) ]

  for i in range( 0, n ) :
    l[ i, i ] = 0
    p[ i, : ] = i + 1

  for j in range( 0, n ) :
    for i in range( 0, n ) :
      if i != j :
        for k in range( 0, n ) :
          if k != j :
            c = l[ i, j ] + l[ j, k ]
            if l[ i, k ] > c :
              l[ i, k ] = c
              p[ i, k ] = p[ j, k ]
  
  return [ l, p ]

In [9]:
l, p = fw_short_path( V, E, cost )
print( l )
print( p )

[[ 0.  4.  5.  6.  6. 11.]
 [inf  0.  3.  2.  2.  7.]
 [inf inf  0.  2.  3.  7.]
 [inf inf inf  0. inf  5.]
 [inf inf inf  4.  0.  5.]
 [inf inf inf inf inf  0.]]
[[1. 1. 1. 2. 2. 4.]
 [2. 2. 2. 2. 2. 4.]
 [3. 3. 3. 3. 3. 4.]
 [4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6.]]
