# Simplex algorithm

Implementation of the simplex algorithm, based on Gaussian pivots

In [12]:
# Numerical python library, importing all
import numpy as np

# Scientific computing python library, importing linalg sections
from scipy import linalg

In [13]:
def gauss_elimination( A, b ) :
    m = A.shape[0]
    n = A.shape[1]
    
    for j in range( 0, n - 1 ) :
        for i in range( j + 1, m ) :
            p = A[ i, j ] / A[ j, j ]
            for k in range( j, n ) :
                A[ i, k ] = A[ i, k ] - p * A[ j, k ]
            
            b[ i ] = b[ i ] - p * b[ j ]
            
    # Backward sustitution
    x = np.copy( b )
    for i in range( m - 1, -1, -1 ) :
        for k in range( i + 1, n ) : 
            x[ i ] = x[ i ] - A[ i, k ] * x[ k ]
        x[ i ] = x[ i ] / A[ i, i ]

    return [ A, b, x ]

In [29]:
m = 8
n = 10
A = 1000 * np.random.rand( m, n )
b = 1000 * np.random.rand( m )
c = 1000 * np.random.rand( n )
# B = np.copy( A )
# c = np.copy( b )

In [18]:
# A, b, x = gauss_elimination( A, b )
# print( x )
# s = B.dot( x ) - c
# linalg.norm( s )

In [55]:
# def simplex_method( c, A, b, d ) :
# base
m = A.shape[0]
n = A.shape[1]
I = range( 0, m )
J = range( m, n )

A1 = A[:,I]
[ A1, b1, x1 ] = gauss_elimination( A1, b )
# print( A1.dot( x1 ) - b[I] )
z1 = c[I].dot( A1.dot( b ) )
print( z1 )
Q = A1.dot( A[:,J] )
r = c[J] - Q.T.dot( c[ I ] )
j = np.argmin( r )
if r[j] < 0 :
  J[j]
  

  
#   return ( X )

3456050080817.38
[-5.66394656e+09 -7.20160536e+09]


9

In [67]:
c = b
print( b )
print( c )
print( A )

[ 828.40965024 -418.91011778 -946.79189275]
[ 828.40965024 -418.91011778 -946.79189275]
[[  122.70612868   877.39197637   135.82578382]
 [    0.          -672.2395001    144.0903042 ]
 [    0.             0.         -1376.45277696]]


In [68]:
X = np.insert( A, 0, c, axis = 0  )
X = np.insert( X, X.shape[1], np.insert( b, 0, 0, axis = 0 ), axis = 1  )
print( X )

[[  828.40965024  -418.91011778  -946.79189275     0.        ]
 [  122.70612868   877.39197637   135.82578382   828.40965024]
 [    0.          -672.2395001    144.0903042   -418.91011778]
 [    0.             0.         -1376.45277696  -946.79189275]]
